[viewer]
    Title = "Go语言博客"
    Description = "Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "xxx"
    Zhihu = "xxx"
    Avatar = "https://img1.baidu.com/it/u=1157571229,2891195927&fm=253&fmt=auto&app=120&f=JPEG?w=800&h=800"
    UserName = "哪吒"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "XG-y4RatbGeHaYcDm474uVBYyfDG5f2pgIx8qZUl"
    QiniuSecretKey = "GFhMucX29If5Rs5xEqICj1Tv-mc5EnPNxO8crQJH"
    Valine = true
    ValineAppid = "TWojjl4R6DV3eEaiAfb16PTv-gzGzoHsz"
    ValineAppkey = "AB1nyR9IBUntAMr7FLlc3BdN"
    ValineServerURL = "https://twojjl4r.lc-cn-n1-shared.com"